const path=require('node:path');
const fs=require('node:fs');
const assert=require('node:assert/strict');
const bundled=path.join(process.env.USERPROFILE||'', '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {chromium}=require(fs.existsSync(bundled)?bundled:'playwright');
const artifacts=path.resolve('.local/e2e');fs.mkdirSync(artifacts,{recursive:true});
const temp=process.argv[2];
(async()=>{
  const cache=path.join(process.env.LOCALAPPDATA||'', 'ms-playwright');
  const alternate=fs.existsSync(cache)?fs.readdirSync(cache).filter(n=>/^chromium_headless_shell-\d+$/.test(n)).sort().reverse().map(n=>path.join(cache,n,'chrome-headless-shell-win64/chrome-headless-shell.exe')).find(p=>fs.existsSync(p)):undefined;
  const browser=await chromium.launch({headless:true,...(!fs.existsSync(chromium.executablePath())&&alternate?{executablePath:alternate}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  async function login(email){
    await page.goto('http://127.0.0.1:8765');
    await page.getByLabel('Email trường').fill('shared@vku.udn.vn');
    await page.getByLabel('Mật khẩu',{exact:true}).fill('Test-Only-Password-2026!');
    await page.getByLabel('Vai trò đăng nhập').selectOption(email.startsWith('head')?'head':email.startsWith('training')?'training':email.startsWith('admin')?'admin':'teacher');
    await page.getByRole('button',{name:'Đăng nhập'}).click();
    await page.getByRole('button',{name:'Đăng xuất'}).waitFor();
    await page.locator('#table').waitFor();
  }
  async function logout(){await page.getByRole('button',{name:'Đăng xuất'}).click();await page.getByRole('heading',{name:'Đăng nhập',exact:true}).waitFor();}
  function finalRow(){return page.locator('tbody tr').filter({hasText:'Bảng điểm cuối kỳ'});}
  async function detail(){await finalRow().getByRole('button',{name:'Mở hồ sơ'}).click();await page.locator('dialog[open]').waitFor();}
  async function uploadOne(){
    const resubmit=finalRow().getByRole('button',{name:'Nộp lại'});
    if(await resubmit.count()){await resubmit.click();await page.waitForFunction(()=>document.querySelector('#upload-target').value!=='0');}
    else{await page.locator('#teaching-courses').getByRole('button',{name:'Nộp điểm Cuối kỳ',exact:true}).click();}
    await page.getByLabel('PDF đã có chữ ký giảng viên').setInputFiles(path.join(temp,'one.pdf'));await page.getByRole('button',{name:'Gửi trưởng khoa'}).click();await finalRow().locator('td .submitted').waitFor();
    await page.locator('#submission-receipt').getByText('Teacher',{exact:true}).waitFor();
    await page.locator('#submission-receipt').getByText('Fingerprint SHA-256:',{exact:false}).first().waitFor();
    assert.equal(await page.locator('#submission-receipt').getByText('Fingerprint SHA-256:',{exact:false}).count(),2);
    assert.match(await finalRow().locator('.signer-summary').innerText(),/Teacher/);
  }
  try{
    await page.goto('http://127.0.0.1:8765');await page.getByRole('heading',{name:'Đăng nhập',exact:true}).waitFor();
    assert.equal(await page.locator('#login-role option').count(),4);
    await page.getByLabel('Email trường').fill('teacher5@vku.udn.vn');
    await page.getByLabel('Mật khẩu',{exact:true}).fill('Test-Only-Password-2026!');
    await page.getByLabel('Vai trò đăng nhập').selectOption('admin');
    await page.getByRole('button',{name:'Đăng nhập'}).click();
    await page.getByText('Tài khoản không có vai trò đã chọn.',{exact:false}).waitFor();
    assert.equal(await page.getByRole('heading',{name:'Đăng nhập',exact:true}).count(),1);
    await page.getByLabel('Vai trò đăng nhập').selectOption('teacher');
    await page.screenshot({path:path.join(artifacts,'login.png'),fullPage:true});
    await login('teacher1@vku.udn.vn');
    assert.equal(await page.getByRole('heading',{name:'Bảng điểm của tôi'}).count(),1);
    assert.equal(await page.locator('#filters [name="department"]').evaluate(e=>e.tagName),'SELECT');
    assert.equal(await page.getByRole('button',{name:'So Khớp',exact:true}).count(),0);
    assert.equal(await page.locator('#filters [name="status"] option[value="submitted"]').innerText(),'Chờ Trưởng khoa duyệt');
    assert.equal(await page.locator('#filters [name="status"] option[value="head_signed"]').innerText(),'Chờ Đào tạo duyệt');
    assert.equal(await page.locator('#filters [name="status"] option[value="archived"]').innerText(),'Hoàn thành');
    await page.getByRole('heading',{name:'Các lớp học phần tôi dạy',exact:true}).waitFor();
    assert.equal(await page.locator('#teaching-courses').getByText('Lớp của GV khác',{exact:true}).count(),0);
    await page.getByLabel('Năm học giảng dạy').selectOption('2023-2024');
    await page.getByLabel('Học kỳ giảng dạy').selectOption('1');
    for(const title of ['Đồ án tốt nghiệp (1)','Đề án (1)','Thực tập (1)','Kiến tập (1)']){
      const course=page.locator('.teaching-course').filter({hasText:title});
      assert.equal(await course.getByRole('button',{name:'Nộp điểm hướng dẫn',exact:true}).count(),1);
      assert.equal(await course.getByRole('button',{name:'Nộp điểm Hội đồng',exact:true}).count(),1);
    }
    await page.getByLabel('Năm học giảng dạy').selectOption('2024-2025');
    await page.getByLabel('Học kỳ giảng dạy').selectOption('2');
    await page.locator('#teaching-courses').getByRole('button',{name:'Nộp điểm thành phần',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#upload-form [name=course_id]').value==='2');
    assert.equal(await page.locator('#assessment-type').inputValue(),'component');
    assert.equal(await page.locator('#assessment-type').isVisible(),false);
    assert.equal(await page.locator('#document-label').isVisible(),false);
    assert.equal(await page.locator('#upload-target').isVisible(),false);
    await page.getByLabel('Năm học giảng dạy').selectOption('2025-2026');
    await page.getByLabel('Học kỳ giảng dạy').selectOption('1');
    await page.locator('#teaching-courses').getByRole('button',{name:'Nộp điểm Cuối kỳ',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#upload-form [name=course_id]').value==='1');
    assert.equal(await page.locator('#assessment-type').inputValue(),'final');
    assert.equal(await page.locator('#document-label').inputValue(),'');
    assert.equal(await page.locator('#upload-target').inputValue(),'0');
    if(process.env.E2E_SIGNATURE_POLICY==='local')await page.getByText('Chế độ local:',{exact:false}).waitFor();
    await uploadOne();
    await page.waitForFunction(()=>document.querySelector('.course-upload[data-assessment="final"]').disabled);
    assert.equal(await page.locator('#teaching-courses .course-upload[data-assessment="component"]').isDisabled(),false);
    assert.equal(await page.locator('#teaching-courses .assessment-status').innerText(),'Chờ Trưởng khoa duyệt');
    assert.equal(await page.locator('#teaching-courses .course-upload[data-assessment="final"]').isVisible(),true);
    await page.locator('#teaching-courses').getByRole('button',{name:'Nộp điểm thành phần',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#assessment-type').value==='component');
    await page.getByLabel('PDF đã có chữ ký giảng viên').setInputFiles(path.join(temp,'component.pdf'));await page.getByRole('button',{name:'Gửi trưởng khoa'}).click();
    await page.locator('tbody tr').filter({hasText:'Bảng điểm thành phần'}).waitFor();assert.equal(await page.locator('tbody tr').count(),2);
    await page.waitForFunction(()=>document.querySelector('.course-upload[data-assessment="component"]').disabled);
    assert.equal(await page.locator('#teaching-courses .assessment-status').count(),2);
    await page.getByLabel('Năm học',{exact:true}).fill('1999-2000');await page.getByRole('button',{name:'Lọc',exact:true}).click();
    await page.getByRole('heading',{name:'Chưa có bảng điểm',exact:true}).waitFor();
    assert.equal(await page.locator('#teaching-courses .course-upload[data-assessment="final"]').isDisabled(),true);
    assert.equal(await page.locator('#teaching-courses .course-upload[data-assessment="component"]').isDisabled(),true);
    await page.getByLabel('Năm học',{exact:true}).fill('');await page.getByRole('button',{name:'Lọc',exact:true}).click();
    await finalRow().waitFor();
    await page.screenshot({path:path.join(artifacts,'teacher.png'),fullPage:true});await logout();
    await login('head2@vku.udn.vn');await detail();
    assert.match(await finalRow().locator('.signer-summary').innerText(),/Teacher/);
    await page.getByText('Người ký trên PDF',{exact:true}).waitFor();
    await page.getByText('Teacher',{exact:true}).waitFor();
    if(process.env.E2E_SIGNATURE_POLICY==='local')await page.getByText('Đã kiểm tra mật mã và tính toàn vẹn · CA/thu hồi chưa xác minh',{exact:true}).waitFor();
    // Another tab switches the cookie to GV while this TK form remains open.
    await page.getByLabel('Lý do trả lại').fill('Không được gửi bằng vai trò khác.');
    const switched=await page.request.post('http://127.0.0.1:8765/__test__/rotate-session',{data:{role:'teacher'}});
    assert.equal(switched.status(),200);
    let unexpectedRejects=0;
    const countReject=request=>{if(request.url().endsWith('/reject')&&request.method()==='POST')unexpectedRejects++;};
    page.on('request',countReject);
    await page.getByRole('button',{name:'Trả lại giảng viên'}).click();
    await page.getByText('Phiên đăng nhập đã đổi tài khoản hoặc vai trò.',{exact:false}).waitFor();
    await page.getByRole('heading',{name:'Bảng điểm của tôi',exact:true}).waitFor();
    assert.equal(unexpectedRejects,0);page.off('request',countReject);
    assert.equal(await finalRow().locator('.badge.submitted').innerText(),'Chờ Trưởng khoa duyệt');
    assert.equal((await page.request.post('http://127.0.0.1:8765/__test__/rotate-session',{data:{role:'head'}})).status(),200);
    await page.goto('http://127.0.0.1:8765');await page.locator('#table').waitFor();await detail();
    // Logging in again under the same identity rotates cookie and token only.
    const rotated=await page.request.post('http://127.0.0.1:8765/__test__/rotate-session',{data:{role:'head'}});
    assert.equal(rotated.status(),200);
    let rejectAttempts=0;
    await page.route('**/api/submissions/*/reject',async route=>{
      rejectAttempts++;
      if(rejectAttempts===1)await route.fulfill({status:403,contentType:'application/json',body:JSON.stringify({detail:'CSRF token không hợp lệ. Tải lại trang rồi thử lại.'})});
      else await route.continue();
    });
    await page.getByLabel('Lý do trả lại').fill('Kiểm tra điểm trước khi ký lần hai.');
    await page.getByRole('button',{name:'Trả lại giảng viên'}).click();await page.locator('td .rejected').waitFor();
    assert.match(await finalRow().locator('.signer-summary').innerText(),/Teacher/);
    assert.match(await finalRow().locator('.signer-summary').innerText(),/SecondTeacher/);
    assert.equal(rejectAttempts,2);await page.unroute('**/api/submissions/*/reject');await logout();
    await login('teacher1@vku.udn.vn');
    assert.equal(await page.locator('#teaching-courses .course-upload[data-assessment="final"]').isEnabled(),true);
    assert.equal(await page.locator('#teaching-courses .course-upload[data-assessment="component"]').isDisabled(),true);
    await page.getByLabel('Năm học',{exact:true}).fill('1999-2000');await page.getByRole('button',{name:'Lọc',exact:true}).click();
    await page.getByRole('heading',{name:'Chưa có bảng điểm',exact:true}).waitFor();
    assert.equal(await page.locator('#teaching-courses .course-upload[data-assessment="final"]').isEnabled(),true);
    await page.reload();await page.locator('#teaching-courses .course-upload[data-assessment="final"]').waitFor();
    await page.locator('#teaching-courses .course-upload[data-assessment="final"]').click();
    await page.waitForFunction(()=>document.querySelector('#upload-target').value==='1');
    assert.equal(await page.locator('#upload-target option:checked').getAttribute('data-version'),'2');
    await page.getByLabel('PDF đã có chữ ký giảng viên').setInputFiles(path.join(temp,'one.pdf'));
    await page.getByRole('button',{name:'Gửi trưởng khoa'}).click();
    await page.locator('#teaching-courses [data-assessment-status="final"]').getByText('Chờ Trưởng khoa duyệt',{exact:true}).waitFor();
    assert.equal(await page.locator('#teaching-courses .course-upload[data-assessment="final"]').isDisabled(),true);
    const resubmitted=await (await page.request.get('http://127.0.0.1:8765/api/submissions')).json();
    assert.equal(resubmitted.total,2);
    assert.equal(resubmitted.items.find(item=>item.assessment_type==='final').id,1);
    assert.equal(resubmitted.items.find(item=>item.id===1).version,3);
    await logout();
    await login('head2@vku.udn.vn');await detail();
    await page.getByLabel('PDF đã ký thêm chữ ký trưởng khoa').setInputFiles(path.join(temp,'two.pdf'));
    await page.getByRole('button',{name:'Nộp đến Phòng Đào tạo'}).click();await page.locator('td .head_signed').waitFor();await logout();
    await login('teacher1@vku.udn.vn');
    await page.locator('#teaching-courses [data-assessment-status="final"]').getByText('Chờ Đào tạo duyệt',{exact:true}).waitFor();
    assert.equal(await page.locator('#teaching-courses .course-upload[data-assessment="final"]').isVisible(),true);
    assert.equal(await page.locator('#teaching-courses .course-upload[data-assessment="final"]').isDisabled(),true);
    await logout();
    await login('training3@vku.udn.vn');await detail();
    const trainingRotated=await page.request.post('http://127.0.0.1:8765/__test__/rotate-session',{data:{role:'training'}});
    assert.equal(trainingRotated.status(),200);
    await page.getByRole('button',{name:'Đóng hồ sơ',exact:true}).click();
    assert.equal(await finalRow().locator('td').nth(3).locator('.badge').innerText(),'Đang chờ P.ĐT duyệt');
    assert.equal(await finalRow().locator('td').nth(3).getByRole('button',{name:'Duyệt',exact:true}).isEnabled(),true);
    assert.equal(await page.locator('tbody tr').filter({hasText:'Bảng điểm thành phần'}).getByRole('button',{name:'Duyệt',exact:true}).count(),0);
    let archiveRequests=0;
    const countArchive=request=>{if(request.url().endsWith('/archive')&&request.method()==='POST')archiveRequests++;};
    page.on('request',countArchive);
    await finalRow().getByRole('button',{name:'Duyệt',exact:true}).click();await page.locator('td .archived').waitFor();
    assert.equal(archiveRequests,1);page.off('request',countArchive);
    assert.equal(await finalRow().locator('.badge').innerText(),'Đã lưu');
    assert.match(await finalRow().locator('.signer-summary').innerText(),/Teacher/);
    assert.match(await finalRow().locator('.signer-summary').innerText(),/SecondTeacher/);
    assert.match(await finalRow().locator('.signer-summary').innerText(),/Head/);
    assert.equal(await finalRow().getByRole('button',{name:'Duyệt',exact:true}).isDisabled(),true);
    await page.reload();await page.locator('td .archived').waitFor();
    assert.match(await finalRow().locator('.signer-summary').innerText(),/Head/);
    assert.equal(await finalRow().getByRole('button',{name:'Duyệt',exact:true}).isDisabled(),true);
    assert.equal(await page.locator('#filters [name="status"] option[value="head_signed"]').innerText(),'Đang chờ P.ĐT duyệt');
    assert.equal(await page.locator('#filters [name="status"] option[value="archived"]').innerText(),'Đã lưu');
    assert.equal(await page.locator('#filters [name="department"]').evaluate(e=>e.tagName),'SELECT');
    await page.getByLabel('Khoa',{exact:true}).selectOption('CNTT');
    await page.getByRole('button',{name:'Lọc',exact:true}).click();await page.locator('td .archived').waitFor();
    assert.equal(await finalRow().locator('td').nth(4).getByRole('button',{name:'So Khớp',exact:true}).count(),1);
    assert.equal((await page.request.post('http://127.0.0.1:8765/__test__/comparison-fixture')).status(),200);
    await page.getByRole('button',{name:'Lọc',exact:true}).click();
    const compareRow=page.locator('tbody tr').filter({hasText:'So khớp thử'});await compareRow.waitFor();
    await compareRow.getByRole('button',{name:'So Khớp',exact:true}).click();
    await page.getByRole('heading',{name:'So Khớp điểm',exact:true}).waitFor();
    const exportPath=path.join(temp,'grade-export.pdf');fs.writeFileSync(exportPath,await (await page.request.get('http://127.0.0.1:8765/__test__/comparison-reference')).body());
    assert.equal(await page.locator('#comparison-file').getAttribute('accept'),'.pdf,application/pdf');
    await page.locator('#comparison-file').setInputFiles(exportPath);
    await page.waitForFunction(()=>document.querySelector('#compare-run')?.disabled===false);
    await page.getByRole('checkbox',{name:'Tôi xác nhận file nguồn',exact:false}).check();
    await page.getByRole('button',{name:'So Khớp điểm',exact:true}).click();
    await page.getByRole('heading',{name:'Khớp với file nguồn đã chọn',exact:true}).waitFor();
    fs.writeFileSync(exportPath,await (await page.request.get('http://127.0.0.1:8765/__test__/comparison-reference?changed=true')).body());
    await page.locator('#comparison-file').setInputFiles(exportPath);
    await page.waitForFunction(()=>document.querySelector('#compare-run')?.disabled===false);
    await page.getByRole('checkbox',{name:'Tôi xác nhận file nguồn',exact:false}).check();
    await page.getByRole('button',{name:'So Khớp điểm',exact:true}).click();
    await page.getByRole('heading',{name:'Có sai khác với file nguồn',exact:true}).waitFor();
    await page.locator('#comparison-result').getByText('24IT001',{exact:false}).waitFor();
    await page.screenshot({path:path.join(artifacts,'comparison.png'),fullPage:true});
    await page.getByRole('button',{name:'Đóng so khớp',exact:true}).click();
    await page.getByLabel('Năm học',{exact:true}).fill('2024-2025');await page.getByRole('button',{name:'Lọc',exact:true}).click();await page.getByRole('heading',{name:'Chưa có bảng điểm'}).waitFor();
    await page.getByLabel('Năm học',{exact:true}).fill('2025-2026');await page.getByRole('button',{name:'Lọc',exact:true}).click();await page.locator('td .archived').waitFor();
    await page.screenshot({path:path.join(artifacts,'archive.png'),fullPage:true});await logout();
    await login('teacher1@vku.udn.vn');
    await page.locator('#teaching-courses [data-assessment-status="final"]').getByText('Hoàn thành',{exact:true}).waitFor();
    assert.equal(await page.locator('#teaching-courses .course-upload[data-assessment="final"]').count(),0);
    assert.equal(await page.locator('#teaching-courses .course-upload[data-assessment="component"]').isVisible(),true);
    await page.reload();
    await page.locator('#teaching-courses [data-assessment-status="final"]').getByText('Hoàn thành',{exact:true}).waitFor();
    assert.equal(await page.locator('#teaching-courses .course-upload[data-assessment="final"]').count(),0);
    await page.screenshot({path:path.join(artifacts,'teacher-completed.png'),fullPage:true});await logout();
    await login('admin4@vku.udn.vn');await page.getByRole('button',{name:'Quản trị hệ thống'}).click();await page.getByRole('heading',{name:'Quản trị hệ thống'}).waitFor();
    await page.locator('#co-teacher-course').selectOption('1');
    assert.equal(await page.locator('#co-teacher-user option[value="1"]').count(),0);
    await page.locator('#co-teacher-user').selectOption('5');
    await page.getByRole('button',{name:'Lưu GV ký thứ hai',exact:true}).click();
    await page.getByText('Đã lưu GV ký thứ hai.',{exact:true}).waitFor();
    await page.waitForFunction(()=>document.querySelector('#co-teacher-course')?.value==='');
    await page.locator('#co-teacher-course').selectOption('1');
    assert.equal(await page.locator('#co-teacher-user').inputValue(),'5');
    await page.locator('#mapping-course').selectOption('1');
    await page.locator('#mapping-final').fill('17210, 17219');await page.locator('#mapping-component').fill('777, 778');
    await page.getByRole('button',{name:'Lưu liên kết bảng điểm',exact:true}).click();
    await page.getByText('Đã lưu liên kết cho từng loại bảng điểm.',{exact:true}).waitFor();
    await page.locator('#mapping-course').selectOption('1');
    assert.equal(await page.locator('#mapping-final').inputValue(),'17210,17219');
    assert.equal(await page.locator('#mapping-component').inputValue(),'777,778');
    await page.getByLabel('Họ tên',{exact:true}).fill('Người dùng thử');await page.getByLabel('Email @vku.udn.vn').fill('newuser@vku.udn.vn');
    await page.getByLabel('Mật khẩu tạm').fill('Test-Only-Password-2026!');await page.locator('#user-form [name=department]').fill('CNTT');
    await page.getByRole('button',{name:'Cấp tài khoản',exact:true}).click();await page.getByText('newuser@vku.udn.vn',{exact:true}).waitFor();
    await page.getByLabel('Ngày giờ kết thúc').fill('2020-01-01T12:00');await page.getByRole('button',{name:'Lưu thời hạn'}).click();await page.getByText('Đã lưu cấu hình.',{exact:true}).waitFor();
    await page.locator('#mapping-form').waitFor();
    await page.locator('#mapping-course').selectOption('1');
    await page.screenshot({path:path.join(artifacts,'admin.png'),fullPage:true});await logout();
    await login('teacher1@vku.udn.vn');assert.equal(await page.getByRole('button',{name:'Gửi trưởng khoa'}).isDisabled(),true);
    assert.equal(await page.locator('#teaching-courses').getByRole('button',{name:'Nộp điểm thành phần',exact:true}).isDisabled(),true);
    assert.equal(await page.locator('#teaching-courses').getByRole('button',{name:'Nộp điểm Cuối kỳ',exact:true}).count(),0);
    await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(artifacts,'mobile.png'),fullPage:true});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile page must not overflow horizontally');
    assert.deepEqual(errors,[],'No browser runtime errors');
    console.log('E2E PASS: multiple gradebooks per course, independent types, explicit resubmit, signing, archive, search, admin, deadline, mobile.');
  }catch(error){await page.screenshot({path:path.join(artifacts,'failure.png'),fullPage:true});throw error;}
  finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
